# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  #端口配置
  port: 8080
  #连接超时时间
  connection-timeout: 5000ms
  servlet:
    #映射项目路径
    context-path: /dbBlog

spring:
  profiles:
    # 环境 开发dev，测试test，生产prod
    active: dev
  jackson:
    serialization:
      # jackson返回时间戳
      write-dates-as-timestamps : true
  servlet:
    multipart:
      #文件上传大小配置
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    #restFul风格：当找不到页面时，正常抛出错误，不跳转页面
    throw-exception-if-no-handler-found: true
    #仅映射static资源文件
    static-path-pattern: /static/**
  resources:
    #restFul风格: 不要为资源文件建立映射
    add-mappings: false
  # redis 配置
  redis:
    host: localhost
    port: 6379
    timeout: 6s #连接池超时时长
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待时间
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空闲连接

#mybatis
mybatis-plus:
  #mapper文件
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.dblearn.article.common.pojo
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty

  #mybatis原生配置
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    #不开启二级缓存
    cache-enabled: false

oss:
  qiniu:
    domain: http://piht5ofif.bkt.clouddn.com
    prefix: dbblog
    accessKey: ENC(pVGOa/io1AnqiEKkDTVORO3W8nzn+vbOl53TeRBIGgCuWvqUEzOAdIBLmdpoYVmsDHESGVc2QzY=)
    secretKey: ENC(UXM3TEuaIuLrPdKuDASHoZExQyOrgGl7PqV/iB0EbHOFhnUSF3bMol8D2qh+QlthccS5QD0fHbM=)
    bucketName: dbblog

jasypt:
  encryptor:
    password: dbblog-jasypt
